@startuml
class app.User {
~ Address address
+ void setAddress(String,String,int)
+ String getAddress()
}


class app.Main {
+ {static} void main(String[])
}

class app.Address {
- String city
- String street
- int building
+ String getCity()
+ void setCity()
+ void setCity(String)
+ String getStreet()
+ void setStreet(String)
+ void setStreet()
+ int getBuilding()
+ void setBuilding(int)
+ void setBuilding()
}


@enduml